# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish-uds-core:
    runs-on: ubuntu-latest
    name: Publish Image

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install UDS CLI
        shell: bash
        # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
        run: brew install defenseunicorns/tap/uds@0.26.2
      
      - name: "Login to GHCR"
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ github.token }}

      - name: Build and Publish
        run: uds run build-and-publish --no-progress
